# Default dining center URL
DEFAULT_URL = "https://dash.swarthmore.edu/menu/dining-center"

# Fun food facts
FUN_FACTS = [
    "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible!",
    "Apples float in water because 25% of their volume is air.",
    "The world's most expensive coffee, Kopi Luwak, comes from civet cat poop!",
    "Carrots were originally purple before they were bred to be orange.",
    "Pineapples can take up to 3 years to grow and mature.",
    "The scientific name for a banana is Musa sapientum, which means 'fruit of the wise men.'",
    "Peanuts aren't technically nuts; they are legumes, like beans and lentils.",
    "Cucumbers are 96% water, making them a hydrating snack!",
    "Tomatoes were once thought to be poisonous, as they belong to the nightshade family.",
    "Chocolate was once used as currency by the ancient Aztecs.",
    "Watermelons are both a fruit and a vegetable! They're related to cucumbers and pumpkins.",
    "Strawberries are the only fruit that have their seeds on the outside.",
    "Potatoes were the first food to be grown in space!",
    "Avocados have more potassium than bananas.",
    "One of the world’s most expensive foods is saffron, which can cost more than $3,000 per kilogram.",
    "White chocolate isn’t technically chocolate; it doesn’t contain cocoa solids.",
    "Broccoli contains more protein per calorie than steak.",
    "Figs are technically not a fruit; they are inverted flowers that rely on wasps for pollination.",
    "The average person eats about 35 tons of food in their lifetime.",
    "Raspberries are a member of the rose family.",
    "There are more than 7,500 varieties of apples grown worldwide.",
    "Peppers come in different heat levels because of capsaicin, which is measured using the Scoville scale.",
    "Ketchup was once sold as a medicine in the 1830s, believed to treat indigestion.",
    "Vanilla is the most labor-intensive crop in the world, which is why it’s expensive.",
    "Cheese is the most stolen food in the world!"
]

HEALTH_FACTS = [
    "Drinking water can help you burn calories. It's known as 'water-induced thermogenesis.'",
    "Walking barefoot on grass has been shown to reduce stress and improve mood.",
    "Laughing 100 times burns about the same number of calories as a 10-minute jog!",
    "Spending time in nature has been proven to lower blood pressure and improve immune function.",
    "Dark chocolate is rich in antioxidants and may improve brain function.",
    "Taking the stairs instead of the elevator burns about 10 calories per minute.",
    "Eating an apple wakes you up better than a cup of coffee, thanks to its natural sugars and fiber.",
    "Sunlight exposure triggers the release of serotonin, a hormone associatedwith boosting mood and helping a person feel calm and focused.", 
    "Getting enough sleep helps regulate the hormones that control hunger, potentially aiding in weight management.", 
    "Avocados are packed with healthy fats that help lower bad cholesterol levels.", 
    "Laughing improves the immune system by increasing the production of antibodies and activating T-cells.", 
    "Broccoli and other cruciferous vegetables contain compounds that may help protect against certain types of cancer.", 
    "Drinking green tea has been linked to a reduced risk of Alzheimer's and Parkinson's disease.", 
    "Spicy foods like chili peppers can temporarily boost metabolism and help you burn more calories.", 
    "Eating a handful of nuts each day can improve heart health and lower the risk of diabetes.", 
    "Your brain uses approximately 20% of the oxygen and blood in your body, despite only weighing about 2% of your total body weight.", "Taking regular breaks from sitting can improve circulation and lower the risk of heart disease.", 
    "A healthy gut is crucial for overall health, as about 70% of the immune system resides in the gut.", "Blueberries are known to improve memory and cognitive function due to their high levels of antioxidants.", 
    "Drinking warm water with lemon first thing in the morning can aid digestion and detoxification.", 
    "The average human body contains about 37 trillion cells!", 
    "Exercise helps boost endorphins, which are natural painkillers and mood enhancers.", 
    "Eating a balanced breakfast can improve focus, concentration, and cognitive performance throughout the day.", 
    "Regular stretching can improve posture and flexibility, reducing the risk of injury.", 
    "Oats are a powerful superfood that helps reduce cholesterol and regulate blood sugar levels.", 
    "Smiling can reduce stress and improve your mood, even if it's a forced smile!", 
    "Staying hydrated is essential for maintaining healthy skin and overall body function." ]